export { default as Navbar } from "./navbar/Navbar";
export { default as Cta } from "./section-cta/Cta";
export { default as VirtualVisit } from "./section-virtual-visit/VirtualVisit";
export { default as Statistics } from "./section-statistics/Statistics";
export { default as Offers } from "./section-offers/Offers";
export { default as Testyimony } from "./section-testimony/Testimony";
export { default as Newsletter } from "./section-newsletter/Newsletter";
export { default as Footer } from "./section-footer/Footer";
export { default as Button } from "./shared/Button/Button";
export { default as OfferCard } from "./shared/OfferCard/OfferCard";
export { default as Container } from "./shared/Container/Container";
export { default as Autocomplete } from "./shared/Autocomplete/ Autocomplete";